# Minimal Configuration Example
# This is the simplest possible configuration for getting started

pipeline:
  name: "minimal_example"

data:
  sources:
    - type: "csv"
      path: "data/sample_data.csv"
  
  train_split: 0.8
  test_split: 0.2

model:
  type: "sklearn"
  parameters:
    algorithm: "RandomForestClassifier"

evaluation:
  metrics: ["accuracy", "f1_score"]